name: build-and-unit-tests

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '**' ]
  schedule:
    - cron: '0 5 * * SUN'
  workflow_dispatch:

jobs:
  build:
    runs-on: [ 'ubuntu-24.04' ]

    steps:
    - uses: actions/checkout@v4.1.7
    - name: set up JDK 17
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Build with Gradle
      run: |
        chmod +x gradlew && ./gradlew build

    - name: Unit test report
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }}
