name: build-app-and-run-unit-tests

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 5 * * SUN'

  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Configure JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle
      - name: Build and run unit tests
        run: chmod +x gradlew && ./gradlew build
      - name: Unit test report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
